[package]
name = "terry-proxy"
version = "0.1.0"
edition = "2018"

[dependencies]
once_cell = "1.8.0"
terraria-protocol = { path = "../terraria-protocol" }
tokio = { version = "1.12.0", features = ["rt", "net", "io-util"] }
